workflows:
  default-workflow:
    name: Default Workflow
    environment:
      vars:
        GRADLEW_PATH: "./gradlew"
    scripts:
      - name: Set Gradle wrapper executable
        script: |
          chmod +x $GRADLEW_PATH
      - name: Install dependencies
        script: |
          $GRADLEW_PATH dependencies
      - name: Clean and build
        script: |
          $GRADLEW_PATH clean
          $GRADLEW_PATH build
    artifacts:
      - build/**/*
    cache:
      paths:
        - ~/.gradle/caches/
        - ~/.gradle/wrapper/
